### ISSUE TITLE
Failed to create application on .net core 3.1

### ISSUE THREAD

**Issue by vimanta** [tgjones/gemini#338] opened 2022-02-01 13:42 UTC
Does the GeminiWpf 1.0.37-beta version support .netcore 3.1? I get this error when I run the app:

"System.Windows.Markup.XamlParseException: "The invocation of the constructor on type :'Gemini.AppBoostrapper' that matches the specified binding constraints threw an exception. 'Line number '10' and line position '22''

"Could not load file or assembly 'Xceed.Wpf.AvalonDock, version=3.6.2.0, Culture=neutral"

**Comment by diluculo** [comment] 2022-02-03 01:25
Things are slightly different, but in my case(#332), I was able to fix the same error by explicitly installing `Dirkster.AvalonDock.Themes.VS2013 v3.6.2` and `Dirkster.AvalonDock v3.6.2`.

Your failed project may be using the latest version of `Dirkster.AvalonDock.Themes.VS2013` (eg v4.60.1). However, in [v4.0](https://github.com/Dirkster99/AvalonDock/wiki/Upgrading-to-V4.0-or-later), the namespaces used have changed from `Xceed.Wpf.AvalonDock` to `AvalonDock` and I think this is the cause of the problem.

**Comment by vimanta** [comment] 2022-02-03 06:54
Hi @diluculo and thank you for your reply.  You were right, this fixes my problem.

**Comment by kornman00** [comment] 2022-08-23 20:03
@vimanta if that fixed your problem, can this issue be closed now?

**Comment by tgjones** [comment] 2022-08-28 07:01
Closing, but please re-open if it's still an issue.

**Closed by tgjones** 2022-08-28 07:01 UTC
