### ISSUE TITLE
Wpf sharpDx integration

### ISSUE THREAD

**Issue by sueds** [tgjones/gemini#130] opened 2015-03-11 03:56 UTC
I'm having some trouble picturing how I could use gemini for my level editor. 
In the example all the asset are always disposed of every time the screen is unload. If I use this technique I can't load an unload all the texture and shader every time I switch screen. Maybe that the way all the editors do it but I'm under the impression that would slow down the editor quite a bit. 

So is there a way to conserve some persistence ?

**Comment by tgjones** [comment] 2015-03-12 10:58
Indeed, you definitely wouldn't want to unload all graphics resources every time you change the active window. Normally, you'd have a separate object, in which you store your scene and all its resources. You might create that object when the user loads a scene file, for example. Then you pass that object to any view models / views that need it.

Does that help?

**Comment by sueds** [comment] 2015-03-12 12:05
Yeah ! Quite a bit. 
I tried this method while looking for an answer. The problem is when you try to load multiple windows( like in maya). So I'll try to explain what I did. 
First I moved the graphics device(I have a custom one since I'm not using the toolkit) to the ViewModel, so instead of creating a new graphics device I just update the bindings for the render target and such. So this method worked but when you have multiple game screens, the editor would stall if I change the active screen then swap back. I try to debug it but I couldn't get any message. 
So my problem boils down to how to manage the life of a Dx device across multiple screens. 
I tried something similar using the gemini sample and found similar problems.

thanks for your time

**Comment by tgjones** [comment] 2015-03-12 13:21
The [DeviceService](https://github.com/tgjones/gemini/blob/master/src/Gemini.Modules.SharpDX/Services/DeviceService.cs) class already manages the lifetime of a device across across multiple screens. Without seeing your code, I'm not sure what the problem is. The main thing is to separate out your graphics resources, from the views that display them. You want the lifetime of the graphics resources to be under your control.

**Comment by sueds** [comment] 2015-03-12 22:36
I did separate the graphics resources from the view and the GraphicsDevice ( not the deviceEx) is in the viewmodel. But the problem I think is whenever you try to reset (or to dispose) your graphics device the objects you created when you first loaded the scene are not working anymore. So your sample works because you are always creating and loading new objects each time your active screen change.  So the solution I though was to stop disposing of the graphicsDevice. Each ViewModel holds it's own graphicsDevice. But whenever I swap screen the editor hangs and do trigger any errors.  
I did try to make the GraphicsDevice static so all the windows share the same graphics device which is never disposed or recreated but there is some problem with screen are adjacent. 

So I've been wondering if I can have multiple dx11 device running ?

my graphicsDevice code 

http://codepaste.net/43jb2u

my imageSource code (d3dImage) 

http://codepaste.net/g8gry2

and my viewModel

http://codepaste.net/b399nu

**Comment by tgjones** [comment] 2015-09-07 14:39
@sueds In Gemini I solve those problems by having the [DeviceService](https://github.com/tgjones/gemini/blob/master/src/Gemini.Modules.SharpDX/Services/DeviceService.cs) class manage a single graphics device for the lifetime of the application. Any views / view models that need the device use that one. 

> I did try to make the GraphicsDevice static so all the windows share the same graphics device which is never disposed or recreated but there is some problem with screen are adjacent.

That sounds like the actual problem that needs to be fixed, but without more details, I can't help.

I'm closing this for now, as it's not a bug in Gemini, but feel free to reply and I'll try to help.

**Closed by tgjones** 2015-09-07 14:39 UTC
