### ISSUE TITLE
Issue with new XCeed extended WPF Toolki

### ISSUE THREAD

**Issue by dimentorium** [tgjones/gemini#281] opened 2018-01-29 12:25 UTC
Hi there,

just made the bad mistake to Update the XCeed toolkit to V3.2 via NUget. The older release which Gemini was built to is no longer within NUget.

The issue that I am facing is, when I open a window (Output or Error) in the bottom region, the whole application crashes. Might it be that some mappings where changed within Xceed that causes these in Gemini? Checked it with my own WIndow, this also crashes, when I try to open in Bottom, but works in any other pane location

Best Regards
Phil

**Comment by palver123** [comment] 2018-02-12 19:40
I ran into the same issue. XCeed 2.7 worked fine, and 3.2 does not. I have tracked down to the following:
Look at file:
https://github.com/tgjones/gemini/blob/master/src/Gemini/Modules/Shell/Controls/LayoutInitializer.cs

``` csharp
private static LayoutAnchorablePane CreateAnchorablePane(
	LayoutRoot layout,
	Orientation orientation,
	string paneName,
	InsertPosition position)
{
	// "First() crashes, because there are only horizontal LayoutPanels and it is looking for a vertical
	var parent = layout.Descendents().OfType<LayoutPanel>().First(d => d.Orientation == orientation);
	 ...
}
```

This piece of code is called from BeforeInsertAnchorable(), like this:

``` csharp
var tool = anchorableToShow.Content as ITool;
if (tool != null)
{
	var preferredLocation = tool.PreferredLocation;
	string paneName = GetPaneName(preferredLocation);
	var toolsPane = layout.Descendents().OfType<LayoutAnchorablePane>().FirstOrDefault(d => d.Name == paneName);
	if (toolsPane == null)
	{
		switch (preferredLocation)
		{
			...
			case PaneLocation.Bottom:
				toolsPane = CreateAnchorablePane(layout, Orientation.Vertical, paneName, InsertPosition.End);
				break;
			...
		}
	}
	...
```

Something has changed in AvalonDock.Layout between version 2.7 and 3.2, that causes the LINQ expression to fail.

**Comment by MichalPavlik** [comment] 2018-02-13 16:24
There is probably problem with deserializing state from the ApplicationState.bin file. After update I noticed that there aren't LayoutAnchorSideControls inside DockingManager (you can see it visualy) so auto-hide  and some other functionalities are broken. Disabling deserialization or deleting ApplicationState.bin file resolved this issue. I can try to figure out why this happens. There are mentioned some fixed bugs in serialization/deserialization in official [release notes](https://xceed.com/release-notes/) since v3.2.

**Comment by MichalPavlik** [comment] 2018-02-13 18:01
Oops, sorry. It seems that null "sides" in DockingManager isn't related problem to nonexisting vertical LayoutPanel.

**Comment by MichalPavlik** [comment] 2018-02-13 18:19
Okay, it's quick fix but it seems to be working...

`var parent = layout.Descendents().OfType<LayoutPanel>().FirstOrDefault(d => d.Orientation == orientation);

            if(parent == null)
            {
                var newLayoutPanel = new LayoutPanel { Orientation = orientation };
                if (layout.RootPanel != null)
                {
                    newLayoutPanel.Children.Add(layout.RootPanel);
                }

                layout.RootPanel = newLayoutPanel;
                parent = newLayoutPanel;
            }`

**Comment by palver123** [comment] 2018-02-14 13:35
Can I somehow replace `Gemini.Modules.Shell.Controls.LayoutInitializer` with my own implementation of `ILayoutUpdateStrategy` in an application using Gemini?

I have tried the following MEF export:

``` csharp
[Export(typeof(ILayoutUpdateStrategy))]
public class HackedLayoutInitializer : ILayoutUpdateStrategy
{
	//...
}
```

If I call `CaliburnMicro.IoC.Get<ILayoutUpdateStrategy>()`, it returns an instance of `HackedLayoutInitializer`. However when I try to reproduce the above error (by opening a new panel on the bottom side), my application still crashes because Gemini seems to use its own strategy (`Gemini.Modules.Shell.Controls.LayoutInitializer`) instead of mine (`HackeLayoutInitializer`).

**Comment by MichalPavlik** [comment] 2018-02-14 14:07
I'm just quickly checking source on GitHub and I'm afraid it's hardcoded in [this file](https://github.com/tgjones/gemini/blob/ad13cda46ad90db79c278be8ac15f8ac5428c428/src/Gemini/Modules/Shell/Views/ShellView.xaml#L86). But I believe you can use your own ShellView instead the provided one...

**Comment by palver123** [comment] 2018-02-14 14:16
Okay I have figured it out. There is no need for MEF. Instead I can do the following:

``` csharp
internal static DockingManager GetDockingManager(IShellView shellView)
{
	var hellView = (ShellView)shellView;
	var managerProperty = hellView.GetType().GetField("Manager", BindingFlags.NonPublic | BindingFlags.Instance);
	var dockingManager = (DockingManager)managerProperty.GetValue(hellView);
	return dockingManager;
}
```

And call it like this:

``` csharp
public class ShellViewModel : Gemini.Modules.Shell.ViewModels.ShellViewModel, 
{
	protected override void OnViewLoaded(object view)
	{
		var dockingManager = LayoutItemStatePersister.GetDockingManager(view as IShellView);
		dockingManager.LayoutUpdateStrategy = new HackedLayoutInitializer();
		base.OnViewLoaded(view);
	}
```

**Comment by JobaDiniz** [comment] 2018-02-21 15:11
Anyone knows how to open a `Tool` in the *document area* programatically?

**Comment by palver123** [comment] 2018-02-21 15:15
Is it related to this issue?

**Comment by hozuki** [comment] 2018-03-02 21:58
Another bug confirmed: hiding the tool windows after first launch causes app crash.

Tool windows performs "auto hide" action (the "pin" icon on its header) correctly on first launch. However, after the application has run once (`ApplicationState.bin` is generated), trying to click that button leads to application crash, a `NullReferenceException` in `Xceed.Wpf.AvalonDock.Layout.LayoutAnchorable.ToggleAutoHide()`.

This bug appears in AvalonDock v3.2 (which is the currently only displayed version on NuGet). After reading this thread, thought maybe it also relates to the malformed XML state store (as mentioned in this thread). So I checked the release notes of WpfTookit and tried to downgrade the `Extended.Wpf.Toolkit` to v2.9 by editing `packages.config` then restoring packages, and the problem disappeared. The pain is I have to manually manage AvalonDock's references after editing `packages.config`.

---

Another question, @palver123 could you explain a little about how to use the inherited `ShellViewModel`? Simply use `[Export(typeof(IShell))]` to export it and Caliburn.Micro returns a `TextBlock` saying its view is missing. Then I have to create a `ShellView` which cannot inherit Gemini's `ShellView` (because the latter is defined in XAML); but I cannot apply the inheritance trick (for example [this one](https://havefuncoding.wordpress.com/2014/10/30/inheritance-of-usercontrol-wpf/)), `IShell`'s operations does not reflect on inner `ContentPresenter`, unless there are some serious wrapper code.

**Comment by MichalPavlik** [comment] 2018-03-03 08:12
I'm pretty sure it's consequence of layout deserialization. Try to add this code into LayoutUtility.cs after layoutSerializer.Deserialize(stream);.

```csharp
if (manager.Layout.LeftSide == null)
{
    manager.Layout.LeftSide = new LayoutAnchorSide();
}

if (manager.Layout.RightSide == null)
{
    manager.Layout.RightSide = new LayoutAnchorSide();
}

if (manager.Layout.TopSide == null)
{
    manager.Layout.TopSide = new LayoutAnchorSide();
}

if (manager.Layout.BottomSide == null)
{
    manager.Layout.BottomSide = new LayoutAnchorSide();
}
```

Btw. I had also problem with view location so I replaced the default one with my own. Try to add this code into AppBootstrapper.PreInitialize().

```csharp
var originalLocator = ViewLocator.LocateForModelType;

ViewLocator.LocateForModelType = (modelType, displayLocation, context) =>
{
    string className = modelType.GetTypeInfo().FullName;
    Type type = modelType.Assembly.GetTypes().FirstOrDefault(t => t.FullName == className.Replace("Model", string.Empty));

    if (type != null)
    {
        return Activator.CreateInstance(type) as UIElement;
    }

    return originalLocator(modelType, displayLocation, context);
};

```

**Comment by palver123** [comment] 2018-03-04 23:25
@hozuki I've tried to strip down our code, this is what I got:

``` csharp
namespace MyGeminiApp
{
    [Export(typeof(Gemini.Framework.Services.IShell))]
    public class ShellViewModel : Gemini.Modules.Shell.ViewModels.ShellViewModel
    {
        public override string DisplayName => "My gemini app";
        public override string StateFile => "MyGeminiApp.State.bin";

        static ShellViewModel()
        {
            Caliburn.Micro.ViewLocator.AddNamespaceMapping(
                typeof(MyGeminiApp.ShellViewModel).Namespace,
                typeof(Gemini.Modules.Shell.Views.ShellView).Namespace);
        }
    }
}
```
Hope this helps. I don't quite understand MEF myself and consider it an awful API. Maybe I missed something...

**Comment by hozuki** [comment] 2018-03-06 02:58
Thanks for the example, @palver123 . It's more like Caliburn.Micro's advanced automapping strategies. MEF does scanning `Export`s and `Import`s and match simple `Import`s and `Export`s with the same contract signatures.

**Comment by AdhamAwadhi** [comment] 2018-03-14 09:03
@palver123 This issue almost happens when run app second time, I noted that Xceed `layoutSerializer.Deserialize` set `Orientation` to `Horizontal` after deserialized. I fixed in my app to manual set to `Vertical` after this line [`layoutSerializer.Deserialize(stream);`](https://github.com/tgjones/gemini/blob/cf4b149f0f0a863818755adf1f120b27ce22103c/src/Gemini/Modules/Shell/Views/LayoutUtility.cs#L69)

`manager.Layout.RootPanel.Orientation = System.Windows.Controls.Orientation.Vertical;`

**Comment by Dirkster99** [comment] 2020-06-06 13:13
Hi @All

Do you still see an issue in the Serialization/deserialization of AvalonDock? If so, please open an issue/PR to [correct the problem at its root](https://github.com/Dirkster99/AvalonDock). If not, I am wondering if this issue could be closed?

**Closed** 2020-06-08 18:54 UTC
